#!/bin/bash

if [[ $# == 0 ]]; then
    printf "[ERROR] usage: get-backup-id <filesystem>\n"
    exit 1
fi

# Absolute path this script is in
SCRIPT_DIR=$(dirname $(readlink -f "$0"))

$SCRIPT_DIR/duc list backups | awk "f{print \$2;f=0} /$1/{f=1}" | sed s/\'//g
